-- 1. 소식(공지사항) 테이블
CREATE TABLE IF NOT EXISTS notices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  is_new BOOLEAN DEFAULT TRUE
);

-- 2. 뉴스 테이블 (외부 기사 링크 및 3~5줄 요약)
CREATE TABLE IF NOT EXISTS news_articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. 포럼 테이블 (올해의 포럼 및 아카이브용 자료)
CREATE TABLE IF NOT EXISTS forums (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year INT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  theme TEXT NOT NULL,
  is_current BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS (Row Level Security) 설정 해제
-- Next.js 서버 액션에서 어드민 비밀번호를 통해 검증하므로, 
-- 초기 단계의 단순화를 위해 RLS를 비활성화합니다.
ALTER TABLE notices DISABLE ROW LEVEL SECURITY;
ALTER TABLE news_articles DISABLE ROW LEVEL SECURITY;
ALTER TABLE forums DISABLE ROW LEVEL SECURITY;

-- 더미 데이터 삽입 (초기 확인용)
INSERT INTO notices (title, is_new) VALUES
  ('2026 노벨사이언스 포럼 사전 등록 안내', true),
  ('운영위원회 신규 위원 위촉 공고', false),
  ('2025 아카이브 발표 자료 업데이트 안내', false);

INSERT INTO news_articles (title, summary, url) VALUES
  ('노벨사이언스 포럼, 2026년 주제 ''AI와 미래'' 발표', '올해로 4회째를 맞는 노벨사이언스 포럼이 2026년 대주제로 ''인공지능과 인류의 미래''를 선정했다고 밝혔다. 글로벌 AI 석학들이 참여할 예정이며, 사전 등록은 다음 주부터 시작된다...', 'https://example.com/news/1'),
  ('제3회 포럼 성공적 마무리... 글로벌 과학계 호평', '기후변화를 주제로 열렸던 작년 포럼의 주요 세션 영상이 오늘 아카이브를 통해 공개되었다. 세계 여러 곳에서 10만 명 이상의 온라인 참여자가 참석했던 이번 행사는...', 'https://example.com/news/2');

INSERT INTO forums (year, title, theme, is_current) VALUES
  (2026, '노벨사이언스 창간 10주년 기념 조찬포럼', 'AI (Artificial Intelligence)', true),
  (2025, '2025 대한민국 노벨사이언스 대상 시상식 & 노벨사이언스포럼', '우리나라 과학기술의 위상과 노벨과학상', false),
  (2024, '2024 노벨사이언스 포럼', '우주 탐사와 신물질', false);
